### ISSUE TITLE
Use the 'pathPrefix' configuration option to specify root directory

### ISSUE THREAD

**Issue by tfukaza** [uclaacm/design-guideline#8]
The current code assumes that the root directory of the website is '/', and all hyperlinks are hard-coded to begin with '/'. We need to change this so the root is '/design-guideline'.

To do this, consider using the templating feature of 11ty. In other words, all links should look like `"ROOT_DIR/what/ever/link"`, where ROOT_DIR is some variable we can change if we need to change the root directory again (which *will* happen when we move this code to a new repo)

**Comment by icevin** [comment]
A baseurl string in site.json is already implemented in some places (holdover from Jekyll) - can be accessed through {{ site.baseurl }}

**Comment by tfukaza** [comment]
It seems in 11ty `site.baseurl` no longer exists, I think we need to replace them with `pathPrefix`: https://www.11ty.dev/docs/filters/url/

**Comment by icevin** [comment]
The default site.baseurl doesn't exist anymore, but to make the conversion easier I mimicked the behavior by putting a site.json in the /data/ folder - pathPrefix does seem like the intended 11ty way to do this though

**Comment by tfukaza** [comment]
Actually that's pretty clever. Once you confirm it works on your local repo dev branch, you can go ahead and make a pull request to master branch and I'll approve it. Thanks for the quick work :).
